import type { NextPage } from "next";
import Head from "next/head";
import Form from "../components/Form";
import Header from "../components/Header";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Search Github</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header />
        <form className="flex place-self-center space-x-3">
          <Form />
        </form>
      </main>
    </div>
  );
};

export default Home;
